env_type: vlabench
task_name: select_fruit
robot: franka

num_envs: 1
total_num_envs: null
group_size: 1
seed: 0

control_mode: ee
action_mode: absolute_ee
reward_mode: success

delta_position_scale: 1.0
delta_rotation_scale: 1.0
delta_position_clip: 0.05
delta_rotation_clip: 0.25

ee_frame_offset: [0.0, -0.4, 0.78]
gripper_open_threshold: 0.1
gripper_open_value: 0.04

ignore_terminations: false
max_episode_steps: 80
max_steps_per_rollout_epoch: 80
auto_reset: false
return_tensors: true
require_pcd: false
reset_wait_step: 10
random_init: true
camera_id: 2
use_extra_views: true
render_height: 256
render_width: 256

video_cfg:
  save_video: false
  info_on_video: false
  video_base_dir: ${runner.logger.log_path}/video/train

init_params: {}
